version: '3.8'

services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    env_file: .env

  # [NEW] Добавляем воркер
  worker:
    build: ./backend
    # Запускаем наш новый скрипт вместо uvicorn
    command: python -m app.worker
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - backend

  frontend:
    build: ./frontend
    # В проде здесь не нужен command, так как Nginx стартует сам.
    # Но для локальной разработки оставим npm run dev, если нужно,
    # или закомментируй, если проверяешь продакшн-сборку.
    # command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:80" # Nginx слушает 80 порт внутри

  bot:
    build: ./bot
    command: python main.py
    env_file: .env
    depends_on:
      - backend